### ISSUE TITLE
.beadignore instead of temp/ folder

### ISSUE THREAD

**Issue by korenmiklos** [e3krisztian/bead#36]
To `bead save` large and complex folders, it would be important to flexibly set which files to ignore. Currently, only files inside `temp/` are ignored. 

Introduce a `.beadignore` file with the same syntax as `.gitignore` to set ignore patterns. (This could live inside `.bead-meta`, but keeping it in root would be more similar to the `git` model.)

`bead new` could create a `.beadignore` with only `temp/` in it. This way the default behavior would remain the same, but advanced users could customize.

**Comment by e3krisztian** [comment]
I like the backward compatible implementation proposal, but I do not see your use case.

`bead`'s main purpose is to approximate reproducibility of computations.  Reproducibility is approximated via transparency: by capturing as much as possible from inputs, code/documentation, and outputs of the computation.  Ignoring some files work against this transparency, so it is discouraged.  However using temporary files during computations is sometimes very convenient, therefore one explicit directory - `temp` - is there whose content is ignored. I would not like to widen the blind spot `temp` already made possible, unless it is really necessary.

`bead` is intended to capture *simple* computations - data transformations/merges/calculations.
Where *simple* means, that program code is maximum 100-200 lines, and there is human manageable (< 7) number of input sources, and only a couple of outputs.
While nothing prevents more code/complex structures, they will cause problems - I propose to separate the complex ones to smaller component beads.

If the computation is really complex and it is very hard to split up, I am sure it is a bad idea to selectively hide some parts of it from the future.

I am willing to reopen this ticket if you have a problem still in scope:reproducibility, that I have not covered above.
