### ISSUE TITLE
`bead input load` should create input folders

### ISSUE THREAD

**Issue by korenmiklos** [e3krisztian/bead#37]
I have a folder with a `.bead-meta/bead` json. There are no input folders. (I did not receive it as a bead.) `bead input load` gives the following error.
```
OSError: [Errno 2] No such file or directory: '/Users/koren/Google Drive/Research/supplier-survey/input'
```

Expected behavior: `bead input load` should create `input/path` from the information available at bead-meta. Much like `git checkout` can check out entire folders.

**Comment by korenmiklos** [comment]
A simple `mkdir input` fixed it.

**Comment by e3krisztian** [comment]
I close it, as it is not an intended/supported use case to put together a working bead environment without the tooling, and a simple workaround fixed your issue
