### ISSUE TITLE
New version to release

### ISSUE THREAD

**Issue by andrasvereckei** [e3krisztian/bead#40]
@e3krisztian Please put the new bead version into release.

**Comment by e3krisztian** [comment]
It is not how releasing of this project works.

Bead will be released when I consider it ready.

Your available options here are:
- ask for status
- grab the current sources and help me out after discussion
- do whatever you want with it (see license)

I suppose you wanted to ask about development status:

I do not know the current state of master, I have not touched it in the
last 5 months, it should work, but it could also be unusable.

Until the next feature is considered ready, you should use the last
release/tag (which is from 2016).

Development continued in another branch, which is not functional, yet.

The new feature (name based branches) definitely needs another month at the
minimum of my spare time. When ready, it will (hopefully) solve a lot of
the current user experience problems (speed, updates). (while potentially
brings a new set of problems - we will see)
