### ISSUE TITLE
bead input update <non-existent-input> error message

### ISSUE THREAD

**Issue by kiss-oliver** [e3krisztian/bead#41]
If you try to update a specific, non-existent input (e.g. true input name is "my_input" and you try "bead input update my-input") only a not too informative AttributeError is returned.

Traceback (most recent call last):
...
AttributeError: 'NoneType' object has no attribute 'kind'

**Comment by e3krisztian** [comment]
I am really sorry, somehow I messed up my github notifications, so was not aware of this ticket until now.
It is fixed now (030e1e5b2ea78054e7714985b704ae90d3c7e55d), and will be released soon.
Thanks for reporting!
