### ISSUE TITLE
Force loading of bead input

### ISSUE THREAD

**Issue by korenmiklos** [e3krisztian/bead#45]
When sharing an open bead during development, .bead-meta may get out of sync with the content of input/. For example, we are versioning .bead-meta, but not input/*. In this case, `bead input load` does not behave as expected. It does not load the appropriate version listed in .bead-meta, even if the version living in input/ is older.

Currently, the only? solution to force load an input is
```
bead input delete whatever
bead input load whatever
```
But this does not respect what is already in .bead-meta and is potentially error prone. 

Recommended behavior:
```
bead input load --force whatever
```
same for `update`.

**Comment by e3krisztian** [comment]
Sorry I just saw this issue - I am rarely checking github, and email notifications is turned off...

Synchronizing workspaces at the file level is not safe in general. Versioning/sharing/changing `.bead-meta` can easily lead to problems (as you have found out), and `input` is intentionally read only to prevent/discourage editing data there.

There is a conceptual problem with file level synchronization: after having a partial workspace synchronization (e.g. the case you described), the workspace potentially becomes invalid: a `bead save` in this state could record a computation that has never happened.

The safe way to share development is via `bead`s: `bead save` and `bead develop`.

----

Working with an invalid workspace is outside the scope of the `bead` tool, so if by some external process results in such an invalid state, it is expected, that the fix will be external as well - the tool might help with messages, but there is no guarantee (in this case it can not recognize the invalid state of inputs after a metadata update).
